<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\ConfigurationPages\ManualTemperatureSensorWidget.razor" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lionk.Core.Razor" Version="2.0.0" />
    <PackageReference Include="MudBlazor" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lionk.Rpi.TemperatureSensor\Lionk.Rpi.TemperatureSensor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\ConfigurationPages\ManualTemperatureSensorWidget.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\ConfigurationPages\ManualTemperatureSensorWidget.razor" />
  </ItemGroup>



</Project>
